/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: {
          50: '#f7f5f2',
          100: '#ede8e1',
          200: '#d9d0c4',
          300: '#c0b3a1',
          400: '#9c8b75',
          500: '#7a6957',
          600: '#5c4f42',
          700: '#3e352c',
          800: '#2a241e',
          900: '#1a1410',
          950: '#0f0c09',
        },
        gold: {
          50: '#fbf8f0',
          100: '#f5ecd6',
          200: '#ecd9ac',
          300: '#dcc07a',
          400: '#c8a96a',
          500: '#b89150',
          600: '#9c783e',
          700: '#7c5e32',
          800: '#5e4827',
          900: '#3e3019',
        },
        wine: {
          50: '#fcf4f4',
          100: '#fae8e8',
          200: '#f5d0d0',
          300: '#eaaeae',
          400: '#d97e7e',
          500: '#c45c5c',
          600: '#a83e3e',
          700: '#8a2f2f',
          800: '#6b2727',
          900: '#4a1c1c',
        },
        cream: '#f7f3ee',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Italiana', '"Cormorant Garamond"', 'serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'fade-up': 'fadeUp 0.8s ease-out forwards',
        'fade-down': 'fadeDown 0.8s ease-out forwards',
        'scale-in': 'scaleIn 0.6s ease-out forwards',
        'slide-right': 'slideRight 0.6s ease-out forwards',
        'slide-left': 'slideLeft 0.6s ease-out forwards',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'kenburns': 'kenburns 20s ease-out infinite alternate',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        'glow': 'glow 3s ease-in-out infinite',
        'marquee': 'marquee 30s linear infinite',
        'spin-slow': 'spinSlow 20s linear infinite',
        'draw-line': 'drawLine 1.5s ease-out forwards',
        'pulse-gold': 'pulseGold 2.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeUp: { '0%': { opacity: '0', transform: 'translateY(30px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeDown: { '0%': { opacity: '0', transform: 'translateY(-30px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        slideRight: { '0%': { opacity: '0', transform: 'translateX(-30px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideLeft: { '0%': { opacity: '0', transform: 'translateX(30px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        shimmer: { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '1' } },
        kenburns: { '0%': { transform: 'scale(1) translate(0, 0)' }, '100%': { transform: 'scale(1.12) translate(-1%, -1%)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        glow: { '0%, 100%': { opacity: '0.3', filter: 'blur(20px)' }, '50%': { opacity: '0.6', filter: 'blur(30px)' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        spinSlow: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        drawLine: { '0%': { width: '0' }, '100%': { width: '100%' } },
        pulseGold: { '0%, 100%': { boxShadow: '0 0 0 0 rgba(200,169,106,0.3)' }, '50%': { boxShadow: '0 0 0 12px rgba(200,169,106,0)' } },
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};
